apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: pvc-nextcloud
      containers:
        - name: nextcloud
          image: nextcloud
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_HOST
              value: nextcloud-db
            - name: MYSQL_PASSWORD
              value: nextcloudpass
            - name: MYSQL_USER
              value: nextcloud
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: adminpass
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
