apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: pvc-mariadb
      containers:
        - name: mariadb
          image: registry.redhat.io/rhel8/mariadb-105
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: nextcloudpass
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_USER
              value: nextcloud
          resources: {}
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
