apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
        - name: patch-trusted-domains
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              CONFIG_FILE="/var/www/html/config/config.php"
              while [ ! -f "$CONFIG_FILE" ]; do
                echo "Waiting for config.php to be created..."
                sleep 2
              done
              echo "Patching trusted_domains..."
              sed -i "/'trusted_domains' =>/{
                N
                s/array ([^)]*)/array (\n    0 => 'localhost',\n    1 => 'nextcloud',\n    2 => 'nextcloud-nextcloud.apps.wzocpdev.vmware.tamlab.rdu2.redhat.com',\n  )/
              }" "$CONFIG_FILE"
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      containers:
        - name: nextcloud
          image: nextcloud
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_HOST
              value: nextcloud-db
            - name: MYSQL_PASSWORD
              value: nextcloudpass
            - name: MYSQL_USER
              value: nextcloud
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: adminpass
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: pvc-nextcloud
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
