apiVersion: apps/v1 # Standard Kubernetes API version for Deployment
kind: Deployment # Standard Kubernetes resource kind
metadata:
  name: nextcloud-db
  namespace: nextcloud
  labels:
    app: nextcloud-db
spec:
  replicas: 1 # Recommended for a database unless you have a highly available setup
  selector:
    matchLabels: # Selector to identify pods managed by this Deployment
      app: nextcloud-db
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      containers:
      - name: mariadb
        image: registry.redhat.io/rhel8/mariadb-105 # Your specified image
        ports:
        - containerPort: 3306 # Default MariaDB port
          name: mariadb-port # Named port for service targeting
        envFrom: # Pulls environment variables from the secret
          - secretRef:
              name: nextcloud-db-credentials # Reference to the Secret for database credentials
        volumeMounts:
        - name: mariadb-storage # Mounts the PVC defined above
          mountPath: /var/lib/mysql # Default data path for MariaDB container
        livenessProbe: # Health check to ensure DB is running and responsive
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe: # Readiness check before sending traffic to the DB
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc # Name of the PVC to claim
  strategy:
    type: Recreate # Ensures old pods are fully terminated before new ones start, suitable for databases
