apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        # Add or update these lines under spec.template.spec.securityContext
        runAsUser: 33   # Set to www-data UID (standard for nextcloud:apache)
        fsGroup: 33     # Set the group ownership for the volume to www-data's GID
         # Ensure it doesn't try to run as root
      containers:
        - name: nextcloud
          image: nextcloud
          env:
            - name: MYSQL_HOST
              value: nextcloud-db
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: nextcloudpass
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: adminpass
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html/data
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc