
apiVersion: apps/v1 # Standard Kubernetes API version for Deployment
kind: Deployment # Standard Kubernetes resource kind
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1 # Number of Nextcloud application replicas
  selector:
    matchLabels: # Selector to identify pods managed by this Deployment
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        # Crucial for Nextcloud on OpenShift to ensure write permissions to mounted volumes.
        # The 'nextcloud:apache' image runs as www-data user (UID 33).
        runAsUser: 33   # Specifies the user ID to run the container process
        fsGroup: 33     # Ensures mounted volumes are owned by GID 33, allowing write access
        
      containers:
      - name: nextcloud
        image: nextcloud:apache # Using the official Nextcloud image with Apache web server
        ports:
        - containerPort: 80 # Nextcloud's Apache listens on port 80 inside the container
          name: http-web # Named port for service targeting
        env:
          # Database connection details (referencing the MariaDB service)
          - name: MYSQL_HOST
            value: nextcloud-db:3306 # Connects to the 'nextcloud-db' service
          # Nextcloud trusted domains and URL for integration with OpenShift Routes
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: "nextcloud-nextcloud.apps.wzocp-nonprod.redhat.com" # <--- IMPORTANT: Verify your OCP domain!
          - name: NEXTCLOUD_URL
            value: "https://nextcloud-nextcloud.apps.wzocp-nonprod.redhat.com" # <--- IMPORTANT: Verify your OCP domain!
          # Recommended Nextcloud performance tuning
          - name: PHP_MEMORY_LIMIT
            value: "512M"
          - name: NEXTCLOUD_OVERWRITEPROTOCOL
            value: "https" # Forces HTTPS for external access via the Route
        envFrom: # Pulls database user/pass and admin credentials from secrets
          - secretRef:
              name: nextcloud-db-credentials # Secret containing database user/pass
          - secretRef:
              name: nextcloud-admin-credentials # Secret containing Nextcloud admin user/pass
        volumeMounts:
        - name: nextcloud-data-storage
          mountPath: /var/www/html/data # Standard mount point for Nextcloud's user files
        livenessProbe: # Kubernetes health check for the Nextcloud application
          httpGet:
            path: /status.php # Nextcloud's built-in health check endpoint
            port: 80
            scheme: HTTP
          initialDelaySeconds: 240 # Give Nextcloud ample time to initialize before probing
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe: # Kubernetes readiness check before sending traffic to the pod
          httpGet:
            path: /status.php
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: nextcloud-data-storage
        persistentVolumeClaim:
          claimName: nextcloud-pvc # Name of the PVC for Nextcloud data
  strategy: # Standard Kubernetes deployment strategy
    type: Recreate # Simple strategy, ensures old pod is fully gone before new one starts.
