apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nextcloud
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd