apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd